//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_17_KosmeticheskayaLaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int ID_Appointment { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.TimeSpan AppointmentTime { get; set; }
        public int FID_Master { get; set; }
        public int FID_Client { get; set; }
        public int FID_Service { get; set; }
        public string Comment { get; set; }
        public string PaymentMethod { get; set; }
        public bool IsCanceled { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual ServiceTypes ServiceTypes { get; set; }
    }
}
