//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR_17_KosmeticheskayaLaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterServices
    {
        public int ID_MasterService { get; set; }
        public int FID_Master { get; set; }
        public int FID_Service { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual ServiceTypes ServiceTypes { get; set; }
    }
}
